server:
   port: 9090
   servlet:
    contextPath: /demo

spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 190618   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
